# Generated by Django 6.0.2 on 2026-08-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('special_instruction', models.TextField(blank=True)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash on Delivery'), ('UPI', 'UPI'), ('Card', 'Card')], max_length=20)),
                ('delivery_type', models.CharField(choices=[('Dine In', 'Dine In'), ('Take Away', 'Take Away'), ('Home Delivery', 'Home Delivery')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
