# Generated by Django 6.0.2 on 2026-08-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0005_customerdetails_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='stock',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
